apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: userdb
  namespace: dsbd
spec:
  serviceName: "userdb"
  replicas: 1
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
        - name: userdb
          # before update - image: mysql:5.6
          image: francescocerruto/userdb:2.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: user
              mountPath: /var/lib/Initializer
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: dsbd_data
  volumeClaimTemplates:
    - metadata:
        name: user
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi

---

# mysql-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: userdb
  # before update: namespace not specified
  namespace: dsbd
spec:
  selector:
    app: userdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP