apiVersion: v1
kind: Service
metadata:
  # before update - name: portfoliotracker-service
  name: portfoliotracker
  namespace: dsbd
spec:
  selector:
    app: portfoliotracker
  ports:
    - port: 9000
      targetPort: 9000
      name: exporter

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # before update - name: portfoliotracker-deploy
  name: portfoliotracker
  namespace: dsbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfoliotracker
  template:
    metadata:
      labels:
        app: portfoliotracker
    spec:
      containers:
        # before update - name: portfoliotracker-container
        - name: portfoliotracker
          image: francescocerruto/portfoliotracker:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_DATABASE
              value: dsbd_data
            - name: MYSQL_HOST
              value: "porttrackdb"
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: BROKER_KAFKA
              value: "kafka:9092"
            - name: CRYPTO_UPDATE_TOPIC
              value: cryptoupdate
            - name: PURCHASE_UPDATE_TOPIC
              value: purchaseupdate
            - name: ALERT_TOPIC
              value: alert
            - name: PROMETHEUS_PORT
              value: "9000"
            - name: ERROR_METRICS
              value: number_error
            - name: KAFKA_METRICS
              value: delivery_time
            - name: OPERATION_METRICS
              value: number_operation
            - name: ERROR_RATE
              value: error_rate
            - name: LABEL
              value: portfolio
            - name: PYTHONUNBUFFERED
              value: "1"

